[DEFAULT]
# All sections below are required unless otherwise specified.
# See https://github.com/fastai/nbdev/blob/master/settings.ini for examples.

### Python library ###
repo = spannerflow
lib_name = %(repo)s
version = 0.0.1
min_python = 3.11
license = apache2
black_formatting = True

### nbdev ###
doc_path = _docs
lib_path = spannerflow
nbs_path = nbs
recursive = True
tst_flags = notest
put_version_in_init = True

### Docs ###
branch = main
custom_sidebar = False
doc_host = https://%(user)s.github.io
doc_baseurl = /%(repo)s
git_url = https://github.com/%(user)s/%(repo)s
title = %(lib_name)s

### PyPI ###
audience = Developers
author = Ofer Katz
author_email = ofer.katz@campus.technion.ac.il
copyright = 2024 onwards, %(author)s
description = 
keywords = nbdev jupyter notebook python
language = English
status = 3
user = DeanLight


requirements = grpcio~=1.67.0
    grpcio-tools~=1.67.0
    aiohttp~=3.10.9
    jinja2~=3.1.4
    nbdev~=2.3.31
    requests~=2.32.3
    networkx~=3.4.2
    singleton-decorator~=1.0.0

dev_requirements = pre-commit~=4.0.0
    isort~=5.13.2
    black~=24.8.0
    types-protobuf~=5.28.0.20240924
    types-requests~=2.32.0.20241016
    ruff~=0.7.0
    mypy~=1.13.0
    pytest~=8.3.3
    pytest-cov~=5.0.0
    pytest-asyncio~=0.24.0
    bandit~=1.7.10
    radon~=6.0.1
    ipython~=8.28.0
    jupyter~=1.1.1
    setuptools_rust~=1.10.2
# console_scripts =
# conda_user = 
# package_data =