# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spannerflow.dataflow.v1 import dataflow_pb2 as dataflow_dot_v1_dot_dataflow__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dataflow/v1/dataflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IEFunctionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunIEFunction = channel.stream_stream(
                '/dataflow.v1.IEFunctionService/RunIEFunction',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.RunIEFunctionRequest.SerializeToString,
                response_deserializer=dataflow_dot_v1_dot_dataflow__pb2.RunIEFunctionResponse.FromString,
                _registered_method=True)


class IEFunctionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunIEFunction(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IEFunctionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunIEFunction': grpc.stream_stream_rpc_method_handler(
                    servicer.RunIEFunction,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.RunIEFunctionRequest.FromString,
                    response_serializer=dataflow_dot_v1_dot_dataflow__pb2.RunIEFunctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataflow.v1.IEFunctionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataflow.v1.IEFunctionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IEFunctionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunIEFunction(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dataflow.v1.IEFunctionService/RunIEFunction',
            dataflow_dot_v1_dot_dataflow__pb2.RunIEFunctionRequest.SerializeToString,
            dataflow_dot_v1_dot_dataflow__pb2.RunIEFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataflowServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddRow = channel.unary_unary(
                '/dataflow.v1.DataflowService/AddRow',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.AddRowRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteRow = channel.unary_unary(
                '/dataflow.v1.DataflowService/DeleteRow',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.DeleteRowRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddCollection = channel.unary_unary(
                '/dataflow.v1.DataflowService/AddCollection',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.AddCollectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/dataflow.v1.DataflowService/DeleteCollection',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCollections = channel.unary_unary(
                '/dataflow.v1.DataflowService/GetCollections',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=dataflow_dot_v1_dot_dataflow__pb2.GetCollectionsResponse.FromString,
                _registered_method=True)
        self.GetCollection = channel.unary_stream(
                '/dataflow.v1.DataflowService/GetCollection',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=dataflow_dot_v1_dot_dataflow__pb2.GetCollectionResponse.FromString,
                _registered_method=True)
        self.RunDataflow = channel.unary_stream(
                '/dataflow.v1.DataflowService/RunDataflow',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.RunDataflowRequest.SerializeToString,
                response_deserializer=dataflow_dot_v1_dot_dataflow__pb2.RunDataflowResponse.FromString,
                _registered_method=True)
        self.LoadFromCSV = channel.unary_unary(
                '/dataflow.v1.DataflowService/LoadFromCSV',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.LoadFromCSVRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveToCSV = channel.unary_unary(
                '/dataflow.v1.DataflowService/SaveToCSV',
                request_serializer=dataflow_dot_v1_dot_dataflow__pb2.SaveToCSVRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class DataflowServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunDataflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadFromCSV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveToCSV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddRow': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRow,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.AddRowRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteRow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRow,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.DeleteRowRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCollection,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.AddCollectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollections,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=dataflow_dot_v1_dot_dataflow__pb2.GetCollectionsResponse.SerializeToString,
            ),
            'GetCollection': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCollection,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.GetCollectionRequest.FromString,
                    response_serializer=dataflow_dot_v1_dot_dataflow__pb2.GetCollectionResponse.SerializeToString,
            ),
            'RunDataflow': grpc.unary_stream_rpc_method_handler(
                    servicer.RunDataflow,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.RunDataflowRequest.FromString,
                    response_serializer=dataflow_dot_v1_dot_dataflow__pb2.RunDataflowResponse.SerializeToString,
            ),
            'LoadFromCSV': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadFromCSV,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.LoadFromCSVRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveToCSV': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveToCSV,
                    request_deserializer=dataflow_dot_v1_dot_dataflow__pb2.SaveToCSVRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataflow.v1.DataflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataflow.v1.DataflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataflowService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataflow.v1.DataflowService/AddRow',
            dataflow_dot_v1_dot_dataflow__pb2.AddRowRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataflow.v1.DataflowService/DeleteRow',
            dataflow_dot_v1_dot_dataflow__pb2.DeleteRowRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataflow.v1.DataflowService/AddCollection',
            dataflow_dot_v1_dot_dataflow__pb2.AddCollectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataflow.v1.DataflowService/DeleteCollection',
            dataflow_dot_v1_dot_dataflow__pb2.DeleteCollectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataflow.v1.DataflowService/GetCollections',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            dataflow_dot_v1_dot_dataflow__pb2.GetCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dataflow.v1.DataflowService/GetCollection',
            dataflow_dot_v1_dot_dataflow__pb2.GetCollectionRequest.SerializeToString,
            dataflow_dot_v1_dot_dataflow__pb2.GetCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunDataflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dataflow.v1.DataflowService/RunDataflow',
            dataflow_dot_v1_dot_dataflow__pb2.RunDataflowRequest.SerializeToString,
            dataflow_dot_v1_dot_dataflow__pb2.RunDataflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadFromCSV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataflow.v1.DataflowService/LoadFromCSV',
            dataflow_dot_v1_dot_dataflow__pb2.LoadFromCSVRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveToCSV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataflow.v1.DataflowService/SaveToCSV',
            dataflow_dot_v1_dot_dataflow__pb2.SaveToCSVRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
