"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto 0
__all__ = ['Config']

# %% ../nbs/00_config.ipynb 2
from dataclasses import dataclass
from pathlib import Path

# %% ../nbs/00_config.ipynb 6
@dataclass
class Config:
    LISTEN_PORT: int
    DATAFLOW_PORT: int
    LISTEN_IP: str = "localhost"
    DATAFLOW_IP: str = "localhost"
    PACKAGE_ROOT = Path(__file__).parent
    GENERATED_RUST_PROJECT_PATH: Path = PACKAGE_ROOT.joinpath("generated_rust")
    RUST_SERVER_LIB_DIR_PATH: Path = PACKAGE_ROOT.joinpath("rust_lib")
    RUST_SERVER_LIB_SRC_FILE_PATH: Path = RUST_SERVER_LIB_DIR_PATH.joinpath(
        "src", "latest.rs"
    )
    RUST_SERVER_PATH: Path = PACKAGE_ROOT.joinpath("rust_grpc_server")
    RUST_TARGET_PATH: Path = PACKAGE_ROOT.joinpath("target", "release")
    TEMPLATES_PATH: Path = PACKAGE_ROOT.joinpath("templates")
    RUST_FILE_TEMPLATE_NAME: str = "rust_dataflow.rs.jinja2"
    LOGS_DIR: Path = Path(__file__).parent.joinpath("logs")
    RUST_SERVER_LOG_PATH: Path = LOGS_DIR.joinpath("rust_server.log")
    RUST_SERVER_BUILD_LOG_PATH: Path = LOGS_DIR.joinpath("rust_server_build.log")
    RUST_SO_BUILD_LOG_PATH: Path = LOGS_DIR.joinpath("rust_so_build.log")
    FEATURE_CACHE: bool = False

    @property
    def LISTEN_ADDRESS(self) -> str:
        return f"{self.LISTEN_IP}:{self.LISTEN_PORT}"

    @property
    def DATAFLOW_ADDRESS(self) -> str:
        return f"{self.DATAFLOW_IP}:{self.DATAFLOW_PORT}"
