"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/60_engine.ipynb.

# %% auto 0
__all__ = ['Engine']

# %% ../nbs/60_engine.ipynb 2
import asyncio
import inspect
import math
import subprocess
import threading
from functools import wraps
from pathlib import Path
from typing import Any, Callable, Generator

import grpc
import networkx as nx
from google.protobuf import empty_pb2
from google.protobuf.json_format import MessageToDict

from .config import Config
from .dataflow.v1 import dataflow_pb2, dataflow_pb2_grpc
from .graph_utils import find_output
from .grpc_server import run_server

# %% ../nbs/60_engine.ipynb 4
class Engine:
    def __init__(
        self,
        config: Config = Config(),
        ie_functions: dict[
            str, tuple[str, Callable[[Any], Any], list[type], list[type]]
        ] = dict(),
    ):
        from spannerflow.rust_dataflow import RustDataflow

        self._config = config
        self._ie_functions = ie_functions
        self._rust_dataflow = RustDataflow(config=config, engine=self)  # type: ignore
        self._is_rust_server_running = False
        self._is_python_server_running = False
        self._rust_server_process: None | subprocess.Popen = None
        self._python_server_task: None | asyncio.Task = None

    @staticmethod
    def ensure_server_running(func):
        @wraps(func)
        async def async_wrapper(self, *args, **kwargs):
            self._run_rust_server_in_background()
            await self._run_python_server_in_background()
            return await func(self, *args, **kwargs)

        @wraps(func)
        def sync_wrapper(self, *args, **kwargs):
            self._run_rust_server_in_background()
            asyncio.run(self._run_python_server_in_background())
            return func(self, *args, **kwargs)

        return async_wrapper if inspect.iscoroutinefunction(func) else sync_wrapper

    def close(self):
        self._stop_rust_server()
        asyncio.run(self._stop_python_server())

    async def _run_python_server_in_background(self) -> None:
        if not self._is_python_server_running:
            self._python_server_task = asyncio.create_task(
                run_server(self._ie_functions)
            )
            self._is_python_server_running = True

    async def _stop_python_server(self):
        if not self._is_python_server_running:
            return
        self._python_server_task.cancel()
        try:
            await self._python_server_task
        except asyncio.CancelledError:
            pass
        self._is_python_server_running = False

    def _run_rust_server_in_background(self) -> None:
        def inner() -> None:
            # TODO: handle port is already in use
            server_path = self._config.RUST_SERVER_PATH
            self._config.LOGS_DIR.mkdir(parents=True, exist_ok=True)
            with open(self._config.RUST_SERVER_LOG_PATH, "a") as log_file:
                self._rust_server_process = subprocess.Popen(
                    [str(server_path)], stdout=log_file, stderr=log_file
                )
                self._rust_server_process.communicate()

        if self._is_rust_server_running:
            return
        threading.Thread(target=inner).start()
        self._is_rust_server_running = True

    def _stop_rust_server(self):
        if not self._is_rust_server_running:
            return
        self._rust_server_process.terminate()
        self._is_rust_server_running = False

    @ensure_server_running
    def save_to_csv(self, collection_name: str, file_path: Path) -> None:
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = dataflow_pb2.SaveToCSVRequest(  # type: ignore
                collection_name=collection_name, file_path=str(file_path)
            )
            stub.SaveToCSV(request)

    @ensure_server_running
    def load_from_csv(self, collection_name: str, file_path: Path) -> None:
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = dataflow_pb2.LoadFromCSVRequest(  # type: ignore
                collection_name=collection_name, file_path=str(file_path)
            )
            stub.LoadFromCSV(request)

    @ensure_server_running
    def add_row(self, collection_name: str, row: list[Any]) -> None:
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = dataflow_pb2.AddRowRequest(  # type: ignore
                collection_name=collection_name,
                row=self._serialize_row(self.get_collections()[collection_name], row),
            )
            stub.AddRow(request)

    def _generate_add_rows_requests(
        self, collection_name: str, schema: list[str], rows: list[list[Any]]
    ) -> Generator[dataflow_pb2.AddRowsRequest, None, None]:  # type: ignore
        yield dataflow_pb2.AddRowsRequest(  # type: ignore
            collection_name=collection_name
        )
        for row in rows:
            yield dataflow_pb2.AddRowsRequest(  # type: ignore
                row=dataflow_pb2.RowRequest(row=self._serialize_row(schema, row))  # type: ignore
            )

    @ensure_server_running
    def add_rows(self, collection_name: str, rows: list[list[Any]]) -> None:
        schema = self.get_collections()[collection_name]
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request_generator = self._generate_add_rows_requests(
                collection_name, schema, rows
            )
            stub.AddRows(request_generator)

    @ensure_server_running
    def delete_row(self, collection_name: str, row: list[Any]) -> None:
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = dataflow_pb2.DeleteRowRequest(  # type: ignore
                collection_name=collection_name,
                row=self._serialize_row(self.get_collections()[collection_name], row),
            )
            stub.DeleteRow(request)

    @ensure_server_running
    def add_collection(
        self,
        collection_name: str,
        schema: list[dataflow_pb2.DataType],  # type: ignore
    ) -> None:
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = dataflow_pb2.AddCollectionRequest(  # type: ignore
                collection_name=collection_name, schema=schema
            )
            stub.AddCollection(request)

    @ensure_server_running
    def delete_collection(self, collection_name: str) -> None:
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = dataflow_pb2.DeleteCollectionRequest(  # type: ignore
                collection_name=collection_name
            )
            stub.DeleteCollection(request)

    @ensure_server_running
    def get_collections(self) -> dict[str, list[str]]:
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = empty_pb2.Empty()
            response = stub.GetCollections(request)
            if "collections" not in MessageToDict(response):
                return dict()
            return {
                d["name"]: d["schema"] for d in MessageToDict(response)["collections"]
            }

    @ensure_server_running
    def get_collection(self, collection_name) -> Generator[list[str], None, None]:
        schema = self.get_collections()[collection_name]
        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = dataflow_pb2.GetCollectionRequest(collection_name=collection_name)  # type: ignore
            response_iterator = stub.GetCollection(request)

            for response in response_iterator:
                yield self._deserialize_row(schema, response.row)

    def set_ie_function(
        self,
        name: str,
        func: Callable[[Any], Any],
        input_types: list[type],
        output_types: list[type],
    ):
        self._ie_functions[name] = (name, func, input_types, output_types)

    def get_ie_function(self, name: str):
        return self._ie_functions[name]

    def del_ie_function(self, name: str):
        del self._ie_functions[name]

    @staticmethod
    def _deserialize_row(schema: list[str], row: list[str]) -> list[Any]:
        new_row: list[Any] = list()
        for col_type, value in zip(schema, row):
            match dataflow_pb2.DataType.Value(col_type):  # type: ignore
                case dataflow_pb2.DataType.DATA_TYPE_STRING:  # type: ignore
                    new_row.append(value)  # alread a string
                case dataflow_pb2.DataType.DATA_TYPE_INT:  # type: ignore
                    new_row.append(int(value))
                case dataflow_pb2.DataType.DATA_TYPE_FLOAT:  # type: ignore
                    if math.isnan(float(value)):
                        raise ValueError(f"Expected float, got {value}")
                    new_row.append(float(value))
                case dataflow_pb2.DataType.DATA_TYPE_BOOL:  # type: ignore
                    if value not in ["true", "false"]:
                        raise ValueError(f"Expected bool, got {value}")
                    new_row.append(value.lower() == "true")
                case _:
                    raise ValueError(f"Unknown data type: {col_type}")
        return new_row

    @staticmethod
    def _serialize_row(schema: list[str], row: list[Any]) -> list[str]:
        new_row = list()
        for col_type, value in zip(schema, row):
            match dataflow_pb2.DataType.Value(col_type):  # type: ignore
                case dataflow_pb2.DataType.DATA_TYPE_STRING:  # type: ignore
                    if not isinstance(value, str):
                        raise ValueError(f"Expected str, got {type(value)}")
                    new_row.append(value)
                case dataflow_pb2.DataType.DATA_TYPE_INT:  # type: ignore
                    if not isinstance(value, int):
                        raise ValueError(f"Expected int, got {type(value)}")
                    new_row.append(str(value))
                case dataflow_pb2.DataType.DATA_TYPE_FLOAT:  # type: ignore
                    if not isinstance(value, (float, int)) or math.isnan(value):
                        raise ValueError(
                            f"Expected float/int, got {value} ({type(value)})"
                        )
                    new_row.append(str(value))
                case dataflow_pb2.DataType.DATA_TYPE_BOOL:  # type: ignore
                    if not isinstance(value, bool):
                        raise ValueError(f"Expected bool, got {type(value)}")
                    new_row.append(str(value).lower())
                case _:
                    raise ValueError(f"Unknown data type: {col_type}")
        return new_row

    @ensure_server_running
    def run_dataflow(
        self,
        reversed_graph: nx.DiGraph,
    ) -> Generator[list[str], None, None]:
        so_path, fn_name = self._rust_dataflow.build_so(reversed_graph)

        with grpc.insecure_channel(self._config.DATAFLOW_ADDRESS) as channel:
            stub = dataflow_pb2_grpc.DataflowServiceStub(channel)
            request = dataflow_pb2.RunDataflowRequest(  # type: ignore
                so_path=str(so_path),
                fn_name=fn_name,
            )
            response_iterator = stub.RunDataflow(request)
            schema_types = reversed_graph.graph["nodes_schema_types_dict"][
                find_output(reversed_graph)
            ]
            for response in response_iterator:
                yield self._deserialize_row(
                    schema_types, [str(item) for item in response.row]
                )
