"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/40_grpc_server.ipynb.

# %% auto 0
__all__ = ['IEFunctionService']

# %% ../nbs/40_grpc_server.ipynb 2
from typing import Any, Callable, Generator

import grpc

from .dataflow.v1 import dataflow_pb2, dataflow_pb2_grpc

# %% ../nbs/40_grpc_server.ipynb 4
class IEFunctionService(dataflow_pb2_grpc.IEFunctionServiceServicer):
    def __init__(
        self,
        ie_functions: dict[
            str, tuple[str, Callable[[Any], Any], list[type], list[type]]
        ],
    ):
        super().__init__()
        self._ie_functions = ie_functions

    def RunIEFunction(
        self,
        request_iterator: Generator[dataflow_pb2.RunIEFunctionRequest, None, None],  # type: ignore
        context,
    ) -> Generator[dataflow_pb2.RunIEFunctionResponse, None, None]:  # type: ignore
        function_name = None
        func = None
        rows = []
        for request in request_iterator:
            if request.HasField("function_name"):
                if function_name is not None:
                    context.set_details("Function name already provided.")
                    context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
                    return
                # Extract the function_name from the first request
                function_name = request.function_name
                func_tuple = self._ie_functions.get(function_name)

                if func_tuple is None:
                    context.set_details(f"IE Function '{function_name}' not found.")
                    context.set_code(grpc.StatusCode.NOT_FOUND)
                    return  # Return early after setting the error
                func = func_tuple[1]

            elif request.HasField("row"):
                if func is None:
                    context.set_details("Function name must be provided before rows.")
                    context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
                    return  # Function name must come first

                rows.append([str(row) for row in request.row.row])

        if function_name is None or func is None:
            context.set_details("No function name provided.")
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            return

        for row in rows:
            res = func(*row)

            for r in res:
                response = dataflow_pb2.RunIEFunctionResponse(  # type: ignore
                    row=[str(cell) for cell in r]
                )
                yield response
