name: pytest-coverage-comment

on: [pull_request]
    
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetching base branch
        run: |
            git fetch -u origin ${{ github.head_ref }}:${{ github.head_ref }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'

      - name: Build coverage file
        run: |
          pytest tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        id: coverageComment

        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Update Readme with Coverage Html
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
      
      - name: Pull latest changes
        run: |
          git config pull.rebase false
          git config --global user.email "xx@xx.xx"
          git config --global user.name "Github actions"
          git pull origin ${{ github.head_ref }} --allow-unrelated-histories

      - name: Commit & Push changes to Readme
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
