name: proto_lint

on: [pull_request]

jobs:
  proto_lint:
    name: proto lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wizhi/setup-buf@v1
        with:
          version: '1.43.0'

      - name: Fetching base branch
        run: |
            git fetch -u origin ${{ github.head_ref }}:${{ github.head_ref }}
      - name: Running linter, checking breaking changes
        run: |
          cd proto
          buf lint